### PR TITLE
Update YM2413 emulation core

### PR DESCRIPTION
**Pull request by Gumball2415**
- [x] Update emu2413 to v1.5.9
- [x] Update YMF281B patches

### CODE REVIEW

**Comment by bbbradsmith** [comment]
There is a system in place for allowing selection of past patch sets for 2413, so we should not simply replace the 2413 patch set like this. Instead create a new set among the existing collection, and make it the default one for when 2413 is requested. That way the user can still access the older patch set.

**Comment by bbbradsmith** [comment]
Your pull request comment just has 3 checkboxes, one unfilled. Is that something that is intended for a different pull request later, or was this a work in progress?

**Comment by Gumball2415** [comment]
it's currently a work in progress. i tried to update emu2149 to v1.30, but there was some current bugs regarding envelope period, and i saw that the author is planning to resolve that soon. digital-sound-antiques/emu2149#3

**Comment by Gumball2415** [comment]
updates to emu2149 will now be in a seperate PR

**Pull request merged**
