### PR TITLE
I've made xgm compile in GNU/Linux

### PR DESCRIPTION
**Pull request by FaTony**
There are still 237 compiler warnings. Kinda speaks about the quality of the code. I plan to make a simple console player in a separate repository and continue fixing bugs and improving the code.

### CODE REVIEW

**Comment by bbbradsmith** [comment]
I can't merge something like this.It is too many changes at once, and of different types. There are problems with this too, for example:
- You have corrupted the japanese text comments and string literals in every file you edited.
- You've replaced char arrays with std::string, this is not a compilation fix, this is a functional change.
- You've replaced windows mutex with C++11 <mutex>; this project is not C++11; this is not a compilation fix, this is a serious change to the project.

If the changes were simpler and to a single purpose I might consider it, but I can't use this.

**Comment by bbbradsmith** [comment]
If you want to continue with a fork of the current version for Linux, I'm glad that you're doing that, but I don't think what you're doing is going to be something I want to pull back into the master branch.

My own plans are to finish up some remaining emulation accuracy stuff, and do one more release of the Windows version, before I begin a massive rewrite/refactor as NSFPlay version 3, which will have a cross-platform goal from the ground up.

**Comment by FaTony** [comment]
Too bad I have barely any idea how NES works. I wanted to have a single repository for NES emulation so all your fixes would benefit everyone. I plan to port everything to C++14 according to my coding standards: https://ftz.fatony.net/contributing/cpp_standards.html Like no char* strings, no raw pointers, no C-style arrays or casts. I would argue that my changes are straightforward upgrades. But whatever, I guess I'll keep developing my fork.

**Comment by FaTony** [comment]
Oops I didn't compile the whole thing in 1 go. It gives 608 compiler warnings.

**Pull request closed without merging**
